Repository AY2223S2-CS2113-T15-2/tp, pull requests merged in 2023-03, with the labels that each got.

#22 Add Basic Password to the SecretMaster
  META-INF/MANIFEST.MF
  docs/AboutUs.md
  docs/team/hosea.md
  docs/team/pics/hosea.jpg
  docs/team/steven.md
  src/main/java/seedu/duke/Command/AddBasicPasswordCommand.java
  src/main/java/seedu/duke/Command/AddNUSNetCommand.java
  src/main/java/seedu/duke/Command/AddStudentIDCommand.java
  src/main/java/seedu/duke/Command/Command.java
  src/main/java/seedu/duke/Command/ExitCommand.java
  src/main/java/seedu/duke/Duke.class
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/exceptions/FolderExistsException.java
  src/main/java/seedu/duke/exceptions/FolderNotEmptyException.java
  src/main/java/seedu/duke/exceptions/FolderNotFoundException.java
  src/main/java/seedu/duke/exceptions/IllegalNameException.java
  src/main/java/seedu/duke/exceptions/NonExistentFolderException.java
  src/main/java/seedu/duke/exceptions/RepeatedIdException.java
  src/main/java/seedu/duke/exceptions/SecretNotFoundException.java
  src/main/java/seedu/duke/secrets/BasicPassword.java
  src/main/java/seedu/duke/secrets/NUSNet.java
  src/main/java/seedu/duke/secrets/Secret.java
  src/main/java/seedu/duke/secrets/StudentID.java
  src/main/java/seedu/duke/storage/SecretEnumerator.java
  src/main/java/seedu/duke/storage/SecretMaster.java
  src/main/java/seedu/duke/storage/SecretSearcher.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  text-ui-test/runjar.sh
  text-ui-test/runtest_mac.sh
Labels: type.Task

#23 Searching
  META-INF/MANIFEST.MF
  docs/AboutUs.md
  docs/team/hosea.md
  docs/team/pics/hosea.jpg
  docs/team/steven.md
  src/main/java/seedu/duke/Command/AddBasicPasswordCommand.java
  src/main/java/seedu/duke/Command/AddNUSNetCommand.java
  src/main/java/seedu/duke/Command/AddStudentIDCommand.java
  src/main/java/seedu/duke/Command/Command.java
  src/main/java/seedu/duke/Command/EditCommand.java
  src/main/java/seedu/duke/Command/ExitCommand.java
  src/main/java/seedu/duke/Command/SearchCommand.java
  src/main/java/seedu/duke/Command/ViewCommand.java
  src/main/java/seedu/duke/Duke.class
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/exceptions/FolderExistsException.java
  src/main/java/seedu/duke/exceptions/FolderNotEmptyException.java
  src/main/java/seedu/duke/exceptions/FolderNotFoundException.java
  src/main/java/seedu/duke/exceptions/IllegalNameException.java
  src/main/java/seedu/duke/exceptions/NonExistentFolderException.java
  src/main/java/seedu/duke/exceptions/RepeatedIdException.java
  src/main/java/seedu/duke/exceptions/SecretNotFoundException.java
  src/main/java/seedu/duke/secrets/BasicPassword.java
  src/main/java/seedu/duke/secrets/NUSNet.java
  src/main/java/seedu/duke/secrets/Secret.java
  src/main/java/seedu/duke/secrets/StudentID.java
  src/main/java/seedu/duke/storage/SecretEnumerator.java
  src/main/java/seedu/duke/storage/SecretMaster.java
  src/main/java/seedu/duke/storage/SecretSearcher.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  text-ui-test/runjar.sh
  text-ui-test/runtest_mac.sh
Labels: type.Epic

#48 Add JUnit tests for Edit and Search commands
  .gitignore
  assets/database.txt
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/SearchCommand.java
  src/main/java/seedu/duke/command/ViewCommand.java
  src/test/java/seedu/duke/command/EditCommandTest.java
  src/test/java/seedu/duke/command/SearchCommandTest.java
Labels: type.Task

#95 Export
  assets/logFiles.txt
  assets/logFiles.txt.lck
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/duke/Backend.java
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/AddBasicPasswordCommand.java
  src/main/java/seedu/duke/command/AddNUSNetCommand.java
  src/main/java/seedu/duke/command/AddStudentIDCommand.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/MenuCommand.java
  src/main/java/seedu/duke/command/SearchCommand.java
  src/main/java/seedu/duke/command/ViewCommand.java
  src/main/java/seedu/duke/storage/SecretMaster.java
  src/test/java/seedu/duke/command/DeleteCommandTest.java
  src/test/java/seedu/duke/command/EditCommandTest.java
  src/test/java/seedu/duke/command/ExitCommandTest.java
  src/test/java/seedu/duke/command/SearchCommandTest.java
  src/test/java/seedu/duke/command/ViewCommandTest.java
  text-ui-test/input.txt
  text-ui-test/runtest.sh
Labels: type.Documentation

#96 Export
  docs/UserGuide.md
Labels: type.Documentation
