Repository AY2223S2-CS2113-T15-2/tp, pull requests merged in 2023-04, with the labels that each got.

#171 Fix Edit command and added JUnit tests
  src/main/java/seedu/duke/command/AddNUSNetCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/secrets/BasicPassword.java
  src/main/java/seedu/duke/secrets/CreditCard.java
  src/main/java/seedu/duke/secrets/CryptoWallet.java
  src/main/java/seedu/duke/secrets/NUSNet.java
  src/main/java/seedu/duke/secrets/StudentID.java
  src/main/java/seedu/duke/storage/SecretMaster.java
  src/test/java/seedu/duke/command/EditCommandTest.java
  src/test/java/seedu/duke/secrets/NUSNetTest.java
  src/test/java/seedu/duke/storage/SecretMasterTest.java
Labels: type.Task

#180 Fix delete multiples and add UML V2.10
  docs/UML/Backend.puml
  docs/UML/SecretStorage.puml
  docs/UML/SecureNUSClassDiagram.puml
  docs/UserGuide.md
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/AddNUSNetCommand.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/secrets/BasicPassword.java
  src/main/java/seedu/duke/secrets/CreditCard.java
  src/main/java/seedu/duke/secrets/CryptoWallet.java
  src/main/java/seedu/duke/secrets/NUSNet.java
  src/main/java/seedu/duke/secrets/StudentID.java
  src/main/java/seedu/duke/storage/SecretMaster.java
  src/test/java/seedu/duke/command/DeleteCommandTest.java
  src/test/java/seedu/duke/command/EditCommandTest.java
  src/test/java/seedu/duke/secrets/NUSNetTest.java
  src/test/java/seedu/duke/storage/SecretMasterTest.java
Labels: type.Bug, type.Documentation

#181 Creation V2.1
  docs/UML/Backend.puml
  docs/UML/SecretStorage.puml
  docs/UML/SecureNUSClassDiagram.puml
  src/main/java/seedu/duke/Ui.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/test/java/seedu/duke/command/DeleteCommandTest.java
Labels: type.Bug, type.Documentation

#183 Draft PPP
  docs/team/kairuler.md
Labels: type.Documentation

#184 Update PPP
  docs/team/deepanjali.md
Labels: type.Documentation

#186 Fix JUnit tests for Edit and View
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/command/SearchCommand.java
  src/main/java/seedu/duke/command/ViewCommand.java
  src/main/java/seedu/duke/storage/SecretMaster.java
  src/test/java/seedu/duke/command/EditCommandTest.java
  src/test/java/seedu/duke/command/ViewCommandTest.java
Labels: type.Bug

#187 Edited UI including printing and formatting of most functions and menu and list functions
  assets/logFiles.txt.1
  assets/logFiles.txt.1.lck
  assets/logFiles.txt.2
  docs/team/deepanjali.md
  docs/team/hosea.md
  src/main/java/seedu/duke/command/MenuCommand.java
  src/main/java/seedu/duke/exceptions/secrets/EmptySecretException.java
  src/main/java/seedu/duke/messages/OperationMessages.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED-UNIX.TXT
  text-ui-test/EXPECTED.TXT
  text-ui-test/assets/logFiles.txt
Labels: type.Enhancement

#189 Fixed problem with empty strings for secret names and folders
  assets/logFiles.txt.1
  src/main/java/seedu/duke/exceptions/secrets/EmptySecretException.java
  src/main/java/seedu/duke/secrets/Secret.java
  src/main/java/seedu/duke/storage/SecretMaster.java
  text-ui-test/assets/logFiles.txt
Labels: type.Bug

#192 Export
  assets/logFiles.txt.2
  assets/logFiles.txt.lck
  src/main/java/seedu/duke/Backend.java
  src/test/java/seedu/duke/BackendTest.java
Labels: type.Bug

#224 Export
  assets/logFiles.txt.1
  docs/AboutUs.md
  docs/team/euzhengxi.md
  docs/team/johndoe.md
  src/main/java/seedu/duke/Backend.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/ACTUAL2.TXT
  text-ui-test/EXPECTED-UNIX.TXT
  text-ui-test/EXPECTED.TXT
  text-ui-test/EXPECTED2-UNIX.TXT
  text-ui-test/EXPECTED2.TXT
  text-ui-test/input.txt
  text-ui-test/input2.txt
  text-ui-test/runtest2.sh
Labels: type.Documentation

#225 Export - Made amendments according to team testing
  assets/logFiles.txt.1
  assets/logFiles.txt.lck
  src/main/java/seedu/duke/Backend.java
  src/main/java/seedu/duke/SecureNUS.java
  src/main/java/seedu/duke/command/AddBasicPasswordCommand.java
  src/main/java/seedu/duke/command/AddCreditCardCommand.java
  src/main/java/seedu/duke/command/AddCryptoWalletCommand.java
  src/main/java/seedu/duke/command/AddNUSNetCommand.java
  src/main/java/seedu/duke/command/AddSecretCommand.java
  src/main/java/seedu/duke/command/AddStudentIDCommand.java
  src/main/java/seedu/duke/command/AddWifiPasswordCommand.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/exceptions/secrets/InvalidCVCNumberException.java
  src/main/java/seedu/duke/secrets/CreditCard.java
  src/main/java/seedu/duke/secrets/CryptoWallet.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/BackendTest.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED-UNIX.TXT
  text-ui-test/EXPECTED.TXT
Labels: type.Bug, type.Enhancement

#227 Cleared issues post PED and team test 1
  assets/logFiles.txt.1
  docs/team/hosea.md
  src/main/java/seedu/duke/SecureNUS.java
  src/main/java/seedu/duke/command/AddBasicPasswordCommand.java
  src/main/java/seedu/duke/command/AddCreditCardCommand.java
  src/main/java/seedu/duke/command/AddSecretCommand.java
  src/main/java/seedu/duke/command/AddWifiPasswordCommand.java
  src/main/java/seedu/duke/command/Command.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/ListCommand.java
  src/main/java/seedu/duke/command/MenuCommand.java
  src/main/java/seedu/duke/command/SaveCommand.java
  src/main/java/seedu/duke/command/ViewCommand.java
  src/main/java/seedu/duke/exceptions/NullFolderException.java
  src/main/java/seedu/duke/exceptions/secrets/InvalidCvcNumberException.java
  src/main/java/seedu/duke/exceptions/secrets/NullSecretException.java
  src/main/java/seedu/duke/messages/ErrorMessages.java
  src/main/java/seedu/duke/messages/InquiryMessages.java
  src/main/java/seedu/duke/messages/OperationMessages.java
  src/main/java/seedu/duke/secrets/CreditCard.java
  src/main/java/seedu/duke/storage/SecretEnumerator.java
  src/main/java/seedu/duke/storage/SecretMaster.java
  src/main/java/seedu/duke/ui/Parser.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/BackendTest.java
  src/test/java/seedu/duke/SecureNUSTest.java
  src/test/java/seedu/duke/command/AddCommandTest.java
  src/test/java/seedu/duke/command/DeleteCommandTest.java
  src/test/java/seedu/duke/command/EditCommandTest.java
  src/test/java/seedu/duke/command/ExitCommandTest.java
  src/test/java/seedu/duke/command/ListCommandTest.java
  src/test/java/seedu/duke/command/ViewCommandTest.java
  src/test/java/seedu/duke/secrets/CreditCardTest.java
  src/test/java/seedu/duke/storage/SecretMasterTest.java
  src/test/java/seedu/duke/storage/SecretSearcherTest.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED-UNIX.TXT
  text-ui-test/EXPECTED.TXT
  text-ui-test/assets/database.txt
  text-ui-test/assets/logFiles.txt
  text-ui-test/input.txt
  text-ui-test/runtest.sh
Labels: type.Bug

#226 Export
  assets/logFiles.txt.1
  assets/logFiles.txt.lck
  src/main/java/seedu/duke/Backend.java
  src/main/java/seedu/duke/SecureNUS.java
  src/main/java/seedu/duke/command/AddBasicPasswordCommand.java
  src/main/java/seedu/duke/command/AddCreditCardCommand.java
  src/main/java/seedu/duke/command/AddCryptoWalletCommand.java
  src/main/java/seedu/duke/command/AddNUSNetCommand.java
  src/main/java/seedu/duke/command/AddSecretCommand.java
  src/main/java/seedu/duke/command/AddStudentIDCommand.java
  src/main/java/seedu/duke/command/AddWifiPasswordCommand.java
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/main/java/seedu/duke/command/EditCommand.java
  src/main/java/seedu/duke/exceptions/secrets/InvalidCvcNumberException.java
  src/main/java/seedu/duke/messages/OperationMessages.java
  src/main/java/seedu/duke/secrets/BasicPassword.java
  src/main/java/seedu/duke/secrets/CreditCard.java
  src/main/java/seedu/duke/secrets/CryptoWallet.java
  src/main/java/seedu/duke/storage/SecretMaster.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/BackendTest.java
  text-ui-test/ACTUAL.TXT
  text-ui-test/EXPECTED-UNIX.TXT
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: type.Bug, type.Enhancement

#233 Add JUnit test
  docs/AboutUs.md
  docs/team/pics/khairul.jpg
  src/main/java/seedu/securenus/SecureNUSLogger.java
  src/main/java/seedu/securenus/command/AddCreditCardCommand.java
  src/main/java/seedu/securenus/command/Command.java
  src/main/java/seedu/securenus/command/ViewCommand.java
  src/main/java/seedu/securenus/ui/Ui.java
  src/test/java/seedu/securenus/BackendTest.java
  src/test/java/seedu/securenus/SecureNUSLogFormatterTest.java
  src/test/java/seedu/securenus/SecureNUSLoggerTest.java
  src/test/java/seedu/securenus/SecureNUSTest.java
  src/test/java/seedu/securenus/command/AddBasicPasswordCommandTest.java
  src/test/java/seedu/securenus/command/AddCommandTest.java
  src/test/java/seedu/securenus/command/AddCreditCardCommandTest.java
  src/test/java/seedu/securenus/command/AddCryptoWalletCommandTest.java
  src/test/java/seedu/securenus/command/AddNUSNetCommandTest.java
  src/test/java/seedu/securenus/command/AddSecretCommandTest.java
  src/test/java/seedu/securenus/command/AddStudentIDCommandTest.java
  src/test/java/seedu/securenus/command/AddWifiPasswordCommandTest.java
  src/test/java/seedu/securenus/command/CommandTest.java
  src/test/java/seedu/securenus/command/ViewCommandTest.java
  src/test/java/seedu/securenus/ui/ParserTest.java
  src/test/java/seedu/securenus/ui/UiTest.java
Labels: type.Enhancement

#258 Finalise JUnit tests
  assets/testDatabase.txt
  src/main/java/seedu/securenus/command/AddCreditCardCommand.java
  src/main/java/seedu/securenus/command/Command.java
  src/main/java/seedu/securenus/ui/Ui.java
  src/test/java/seedu/securenus/SecureNUSLogFormatterTest.java
  src/test/java/seedu/securenus/SecureNUSTest.java
  src/test/java/seedu/securenus/command/AddCreditCardCommandTest.java
  src/test/java/seedu/securenus/ui/UiTest.java
Labels: type.Enhancement

#259 Clean up PPP
  docs/team/kairuler.md
  src/test/java/seedu/securenus/ui/ParserTest.java
Labels: type.Documentation

#261 Minor bug in AboutUs.md
  docs/AboutUs.md
Labels: type.Bug, type.Documentation

#264 Add final DG
  docs/DGDiagramsCreator/Basic_Intro.png
  docs/DGDiagramsCreator/DGUsedDiagrams/image23.png
  docs/DGDiagramsCreator/Delete_Intro.png
  docs/DGDiagramsCreator/List_intro.png
  docs/DGimages/image1.png
  docs/DGimages/image10.png
  docs/DGimages/image11.png
  docs/DGimages/image12.png
  docs/DGimages/image13.png
  docs/DGimages/image14.png
  docs/DGimages/image15.png
  docs/DGimages/image16.png
  docs/DGimages/image17.png
  docs/DGimages/image18.png
  docs/DGimages/image19.png
  docs/DGimages/image2.png
  docs/DGimages/image20.png
  docs/DGimages/image21.png
  docs/DGimages/image22.png
  docs/DGimages/image23.png
  docs/DGimages/image24.png
  docs/DGimages/image25.png
  docs/DGimages/image26.png
  docs/DGimages/image27.png
  docs/DGimages/image28.png
  docs/DGimages/image29.png
  docs/DGimages/image3.png
  docs/DGimages/image30.png
  docs/DGimages/image4.png
  docs/DGimages/image5.png
  docs/DGimages/image6.png
  docs/DGimages/image7.png
  docs/DGimages/image8.png
  docs/DGimages/image9.png
  docs/DeveloperGuide.md
Labels: type.Documentation
